- name: talk to esx
  hosts: 192.168.1.23
  become: False
  gather_facts: False
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
