- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: True
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
