- name: talk to esx
  hosts: infra
  become: False
  gather_facts: False
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
      hostname: "{{ inventory_hostname }}"
      username: root
      password: letmein
      validate_certs: no
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
