- name: Install Home Automation System
  hosts: "{{ HOST_GROUP_TO_INCLUDE }}"
  become: true
  tasks:
  - name: installed required packages
    yum:
      name: "{{ item }}"
    with_items:
      - git
      - python 
  - name: Create directory
    file: 
      path: /usr/scripts/
      state: directory
  - name: Clone Git Repository
    git: 
      repo: https://github.com/blambo10/HomeAutomationSystemClient.git
      dest: /usr/scripts/ 
      force: yes
    register: host_facts
  - debug: msg={{ host_facts }}
