- name: Install Home Automation System
  hosts: "{{ HOST_GROUP_TO_INCLUDE }}"
  become: true
  tasks:
  - name: installed required packages
    yum:
      name: "{{ item }}"
    with_items:
      - git
      - python 
  - name: Install Python module for networking
    easy_install:
      name: configparser
  - name: Create directory
    file: 
      path: "{{ installation_directory }}"
      state: directory
  - name: Clone Git Repository
    git: 
      repo: https://github.com/blambo10/HomeAutomationSystemClient.git
      dest: "{{ installation_directory }}"
      force: yes
  - name: copy HASagent config
    template: 
      src: templates/hasagent.config dest=/usr/scripts/has/hasagent.config mode=0644
  - name: copy Service
    template: src=templates/HASagent.service dest=/usr/lib/systemd/system/HASagent.service 
  - name: Allow HAS in the firewall
    command: firewall-cmd --add-rich-rule 'rule family="ipv4" port protocol="tcp" port="6060" accept' --permanent
  - name: Reload firewalld
    command: firewall-cmd --reload
    register: host_facts
  - debug: msg={{ host_facts }}
