- name: Install Home Automation System
  hosts: "{{ HOST_GROUP_TO_INCLUDE }}"
  become: true
  tasks:
  - name: Add epel repo to host
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  - name: installed required packages
    yum:
      name: "{{ item }}"
    with_items:
      - git
      - python
      - python-virtualenv
      - python2-pip
      - python3-pip
      - ansible
      - platform
  - name: Update pip
    pip:
      name: pip
      state: latest
  - name: Install Python module for networking
    pip:
      name: 
        - configparser
        - ipaddress
  - name: Create directory
    file: 
      path: "{{ installation_directory }}"
      state: directory
  - name: Clone Git Repository
    git: 
      repo: https://github.com/blambo10/HomeAutomationSystemClient.git
      dest: "{{ installation_directory }}"
      force: yes
  - name: copy HASagent config
    template: src=templates/hasagent.config dest="{{ installation_directory }}/hasagent.config" mode=0644
  - name: copy Service
    template: src=templates/HASagent.service dest=/usr/lib/systemd/system/HASagent.service 
  - name: Check if firewalld is running
    command: systemctl status firewalld
    register: firewallstat
    ignore_errors: true
    failed_when: "'dynamic firewall daemon' not in firewallstat.stdout"
  - name: Allow HAS in the firewall
    command: firewall-cmd --add-rich-rule 'rule family="ipv4" port protocol="tcp" port="6060" accept' --permanent
    when:  firewallstat.stdout.find('running') != -1
    ignore_errors: true
  - name: Reload firewalld
    command: firewall-cmd --reload
    when:  firewallstat.stdout.find('running') != -1
  - name: Reload Service Daemon
    command: systemctl daemon-reload
    when:  firewallstat.stdout.find('running') != -1
  - name: Enable service httpd, and not touch the running state
    service:
      name: HASagent
      enabled: yes
      state: started
    register: host_facts
  #- debug: msg={{ host_facts }}
  - debug: msg={{ firewallstat }}
