- name: Testing Github Webhooks
  hosts: localhost
  become: False
  gather_facts: False
  tasks:
  - name: "Testing provisioning callback"
    shell: echo "nameserver 192.168.1.1" >> /etc/resolv.conf
