- name: Testing Tags
  hosts: "{{ HOSTS_TO_INCLUDE }}"
  become: False
  gather_facts: False
  tasks:
  - name: Import Vault Files
    include_vars:
      file: "../../vault-files/vsphere-vault.yml"
    #no_log: true
  - name: Extract Tags
    vmware_object_role_permission:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_password }}"
      recursive: no
      role: testy
      principal: bryce
      object_type: Folder
      object_name: testFolder
      state: present
      validate_certs: no
      datacenter: "{{ dcstored }}"
      tags: yes
      validate_certs: no
    delegate_to: localhost
  #- debug: msg="{{ vmDataFromGuestFact }}"
