- name: Testing Tags
  hosts: "{{ HOSTS_TO_INCLUDE }}"
  become: False
  gather_facts: False
  tasks:
  - name: Import Vault Files
    include_vars:
      file: "../../vault-files/vsphere-vault.yml"
    #no_log: true
  - name: Gather vmware host facts
    vmware_vm_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_password }}"
      validate_certs: no
    delegate_to: localhost
    register: virtualMachineFacts
  - name: Extract Tags
    vmware_guest_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vc_username }}"
      password: "{{ vc_password }}"
      uuid: "{{ item.value.uuid }}"
      datacenter: "{{ dcstored }}"
      tags: yes
      validate_certs: no
    delegate_to: localhost
    loop: "{{ lookup('dict', virtualMachineFacts.virtual_machines) }}"
    register: vmDataFromGuestFact
  - debug: msg="{{ vmDataFromGuestFact }}"
