- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  tasks:
  - name: Gather kernel data
    vmware_guest:
      hostname: "{{ inventory_hostname }}" 
      username: "{{ username }}"
      password: "{{ password }}"
      #datacenter: Datacenter
      validate_certs: no
      name: "centos 7"
      
     #folder: "/Datacenter/vm"
#      cdrom:
#        type: iso 
#        iso_path: "[datastore1] centos.iso"
      #state: "{{ vmPowerState }}"
      #hardware:
      #  memory_mb: 3000
      #  num_cpus: 2 
      customvalues: 
        - key: "isolation.device.edit.disabled"
          value: "true"
        - key: "machines-limit-setinfo-size"
          value: "1048576"
    register: host_facts
    delegate_to: localhost
  - debug: msg={{ host_facts }}
  #- name: dump object
  #- debug: msg="{{ host_facts.host_vmk_facts }}"
