- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  tasks:
  - name: Gather vmware host facts
    vmware_host_config_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      esxi_hostname: 192.168.1.23
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
