- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  tasks:
  - name: Gather kernel data
    vmware_vmkernel_facts:
      hostname: 192.168.1.70
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      esxi_hostname: "{{ inventory_hostname }}" 
    register: host_facts
    delegate_to: localhost
  - name: extract port group
    set_fact:
      #pgroup: "{{ host_facts }}"
      pgroup: "{{ host_facts.host_vmk_facts | json_query('*') }}"
#    register: pgroup
  - debug: msg={{ pgroup }}
  #- name: dump object
  #- debug: msg="{{ host_facts.host_vmk_facts }}"
