- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
      hostname: 192.168.1.23
      username: root
      password: letmein
      validate_certs: no
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
