- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  tasks:
  - name: Proof Of Concept TSS Network Security
    vmware_portgroup:
      hostname: 192.168.1.70
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      hosts: 192.168.1.23
      switch_name: vSwitch0
      portgroup_name: "test"
      vlan_id: "0"
      network_policy:
          promiscuous_mode: False
#      network_policy:
#        promiscuous_mode: False
#        mac_changes: False
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
