- name: ssh user management
  hosts: all
  # become: False
  # gather_facts: False
  tasks:

  #[BL] Complete login to get default root
  #     then use the default root to login to the server intially if success set p/w in vault then reset on server 
  - name: Get Default root user from vault
    uri:
      url: 'https://{{ VAULT_SERVER_ADDRESS }}:{{ VAULT_SERVER_PORT }}/v1/secret/{{ HASHI_PATH }}'
      # status_code: [200, 202]
      method: GET
      return_content: false
      headers:
        X-Vault-Token: "{{ ansible_password }}"
        Content-Type: application/json
    register: shh_credentials

  # - name: Login to a form based webpage, then use the returned cookie to access the app in later tasks
  #   uri:
  #     url: https://your.form.based.auth.example.com/index.php
  #     method: POST
  #     body_format: form-urlencoded
  #     body:
  #       name: your_username
  #       password: your_password
  #       enter: Sign in
  #     status_code: 302
  #   register: login
  

  # - name: Testing
  #   shell: hostname