- name: talk to esx
  hosts: vmware
  become: False
  gather_facts: False
  vars:
    vmware:
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vmware.username }}"
      password: "{{ vmware.password }}"
      validate_certs: no
      name: "centos 7"
      hardware:
        memory_mb: 4000
        num_cpus: 3 
    register: host_facts
    delegate_to: localhost
  - debug: msg={{ host_facts }}
  #- name: dump object
  #- debug: msg="{{ host_facts.host_vmk_facts }}"
