- name: talk to esx
  hosts: infra
  become: False
  gather_facts: False
  - name: Importing Secrets
    include_vars:
      file: "../vault-files/{{ VAULT_FILE }}"
  tasks:
  - name: Gather vmware host facts
    vmware_host_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ esx-username }}"
      password: "{{ esx-password }}"
      validate_certs: no
    register: host_facts
    delegate_to: localhost
  - debug: msg="{{ host_facts }}"
